---
name: Setup shfmt
description: Download the shfmt binary and add it to the PATH
author: Mario Finelli
inputs:
  shfmt-version:
    description: Version of shfmt to download
    required: false
    default: latest
runs:
  using: node24
  main: dist/index.js
branding:
  icon: terminal
  color: purple
